# Makefile generated by BNFC.

# List of goals not corresponding to file names.

.PHONY : all clean distclean

# Default goal.

all : Sum/Test

# Rules for building the parser.

Sum/ErrM.hs Sum/Lex.x Sum/Print.hs Sum/Par.y Sum/Test.hs : Sum.cf
	bnfc --haskell -d Sum.cf

%.hs : %.y
	happy --ghc --coerce --array --info $<

%.hs : %.x
	alex --ghc $<

Sum/Test : Sum/Test.hs Sum/ErrM.hs Sum/Lex.hs Sum/Par.hs Sum/Print.hs
	ghc --make $< -o $@

# Rules for cleaning generated files.

clean :
	-rm -f Sum/*.hi Sum/*.o Sum/*.log Sum/*.aux Sum/*.dvi

distclean : clean
	-rm -f Sum/Abs.hs Sum/Abs.hs.bak Sum/ComposOp.hs Sum/ComposOp.hs.bak Sum/Doc.txt Sum/Doc.txt.bak Sum/ErrM.hs Sum/ErrM.hs.bak Sum/Layout.hs Sum/Layout.hs.bak Sum/Lex.x Sum/Lex.x.bak Sum/Par.y Sum/Par.y.bak Sum/Print.hs Sum/Print.hs.bak Sum/SharedString.hs Sum/SharedString.hs.bak Sum/Skel.hs Sum/Skel.hs.bak Sum/Test.hs Sum/Test.hs.bak Sum/XML.hs Sum/XML.hs.bak Sum/AST.agda Sum/AST.agda.bak Sum/Parser.agda Sum/Parser.agda.bak Sum/IOLib.agda Sum/IOLib.agda.bak Sum/Main.agda Sum/Main.agda.bak Sum/Sum.dtd Sum/Sum.dtd.bak Sum/Test Sum/Lex.hs Sum/Par.hs Sum/Par.info Sum/ParData.hs Makefile
	-rmdir -p Sum/

# EOF
