-- Haskell module generated by the BNF converter

module CPP.Skel where

import qualified CPP.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transId :: CPP.Abs.Id -> Result
transId x = case x of
  CPP.Abs.Id string -> failure x
transProgram :: CPP.Abs.Program -> Result
transProgram x = case x of
  CPP.Abs.PDefs defs -> failure x
transDef :: CPP.Abs.Def -> Result
transDef x = case x of
  CPP.Abs.DFun type_ id args stms -> failure x
transArg :: CPP.Abs.Arg -> Result
transArg x = case x of
  CPP.Abs.ADecl type_ id -> failure x
transStm :: CPP.Abs.Stm -> Result
transStm x = case x of
  CPP.Abs.SExp exp -> failure x
  CPP.Abs.SDecls type_ ids -> failure x
  CPP.Abs.SInit type_ id exp -> failure x
  CPP.Abs.SReturn exp -> failure x
  CPP.Abs.SReturnVoid -> failure x
  CPP.Abs.SWhile exp stm -> failure x
  CPP.Abs.SBlock stms -> failure x
  CPP.Abs.SIfElse exp stm1 stm2 -> failure x
transExp :: CPP.Abs.Exp -> Result
transExp x = case x of
  CPP.Abs.ETrue -> failure x
  CPP.Abs.EFalse -> failure x
  CPP.Abs.EInt integer -> failure x
  CPP.Abs.EDouble double -> failure x
  CPP.Abs.EString string -> failure x
  CPP.Abs.EId id -> failure x
  CPP.Abs.EApp id exps -> failure x
  CPP.Abs.EPIncr exp -> failure x
  CPP.Abs.EPDecr exp -> failure x
  CPP.Abs.EIncr exp -> failure x
  CPP.Abs.EDecr exp -> failure x
  CPP.Abs.ETimes exp1 exp2 -> failure x
  CPP.Abs.EDiv exp1 exp2 -> failure x
  CPP.Abs.EPlus exp1 exp2 -> failure x
  CPP.Abs.EMinus exp1 exp2 -> failure x
  CPP.Abs.ELt exp1 exp2 -> failure x
  CPP.Abs.EGt exp1 exp2 -> failure x
  CPP.Abs.ELtEq exp1 exp2 -> failure x
  CPP.Abs.EGtEq exp1 exp2 -> failure x
  CPP.Abs.EEq exp1 exp2 -> failure x
  CPP.Abs.ENEq exp1 exp2 -> failure x
  CPP.Abs.EAnd exp1 exp2 -> failure x
  CPP.Abs.EOr exp1 exp2 -> failure x
  CPP.Abs.EAss exp1 exp2 -> failure x
  CPP.Abs.ETyped exp type_ -> failure x
transType :: CPP.Abs.Type -> Result
transType x = case x of
  CPP.Abs.Type_bool -> failure x
  CPP.Abs.Type_int -> failure x
  CPP.Abs.Type_double -> failure x
  CPP.Abs.Type_void -> failure x
  CPP.Abs.Type_string -> failure x

